import crypto from 'crypto';

export const RAZORPAY_KEY_ID = (
  process.env.RAZORPAY_KEY_ID ||
  process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID ||
  'rzp_live_TgneYi4y1wFtMS'
).trim();

export const RAZORPAY_KEY_SECRET = (
  process.env.RAZORPAY_KEY_SECRET || 'hxgQBYqgXGAJ3mK1p6Ph9mhs'
).trim();

export interface RazorpayOrderResponse {
  id: string;
  entity: string;
  amount: number;
  amount_paid: number;
  amount_due: number;
  currency: string;
  receipt: string;
  status: string;
  attempts: number;
  notes: Record<string, any>;
  created_at: number;
}

/**
 * Creates a Razorpay order via the official REST API.
 * @param amountInInr Price in Rupees (e.g. 299)
 * @param receipt Unique receipt ID (e.g. sub_123456)
 * @param notes Custom metadata attached to the order
 */
export async function createRazorpayOrder(
  amountInInr: number,
  receipt: string,
  notes?: Record<string, string>
): Promise<RazorpayOrderResponse> {
  const amountInPaise = Math.round(amountInInr * 100);

  const keyId = (
    process.env.RAZORPAY_KEY_ID ||
    process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID ||
    'rzp_live_TgneYi4y1wFtMS'
  ).trim();

  const keySecret = (
    process.env.RAZORPAY_KEY_SECRET || 'hxgQBYqgXGAJ3mK1p6Ph9mhs'
  ).trim();

  if (!keyId || !keySecret) {
    throw new Error('Razorpay API keys (Key ID or Key Secret) are missing in environment variables.');
  }

  const authHeader = `Basic ${Buffer.from(
    `${keyId}:${keySecret}`
  ).toString('base64')}`;

  const response = await fetch('https://api.razorpay.com/v1/orders', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: authHeader,
    },
    body: JSON.stringify({
      amount: amountInPaise,
      currency: 'INR',
      receipt: receipt.slice(0, 40), // Razorpay limit: 40 chars
      notes: notes || {},
    }),
  });

  const data = await response.json();

  if (!response.ok) {
    console.error('Razorpay order creation failed:', data);
    if (
      response.status === 401 ||
      data.error?.description?.toLowerCase().includes('authentication')
    ) {
      throw new Error(
        'Razorpay Authentication Failed: Invalid Key ID or Key Secret. Please verify your Razorpay API Keys in Razorpay Dashboard.'
      );
    }
    throw new Error(data.error?.description || 'Failed to create Razorpay order');
  }

  return data as RazorpayOrderResponse;
}

/**
 * Validates the HMAC-SHA256 signature generated by Razorpay Checkout.
 */
export function verifyRazorpaySignature(
  orderId: string,
  paymentId: string,
  signature: string
): boolean {
  if (!orderId || !paymentId || !signature) return false;

  const keySecret = (
    process.env.RAZORPAY_KEY_SECRET || 'hxgQBYqgXGAJ3mK1p6Ph9mhs'
  ).trim();

  const expectedSignature = crypto
    .createHmac('sha256', keySecret)
    .update(`${orderId}|${paymentId}`)
    .digest('hex');

  return expectedSignature === signature;
}
